---
refresh_interval: 2 # seconds
max_price: 630 # dollars
urls:
#Amazon	
  - https://www.amazon.fr/PlayStation-%C3%89dition-Standard-DualSense-Couleur/dp/B08H93ZRK9
  - https://www.amazon.fr/PlayStation-Digital-Manette-DualSense-Couleur/dp/B08H98GVK8
  - https://www.amazon.fr/dp/B08H99878P/ref=emc_b_5_i
#Fnac
  - https://jeux-video.fnac.com/Console-Sony-PS5-Edition-Standard/a16164926/w-4#int=S:%3Cb%3ELe%20jeu%20n'a%20pas%20de%20limites%3C-b%3E|PS5|NonApplicable|NonApplicable|BL1|L1
  - https://www.fnac.com/Console-Sony-PS5-Edition-Digital/a14119961/w-4#int=S:%3Cb%3ELe%20jeu%20n'a%20pas%20de%20limites%3C-b%3E|PS5|NonApplicable|NonApplicable|BL2|L1
#Micromania
  - https://www.micromania.fr/playstation-5-105642.html
  - https://www.micromania.fr/playstation-5-alldigital-106097.html  

#Boulanger
  - https://www.boulanger.com/ref/1147567
  - https://www.boulanger.com/ref/1147568
  - https://www.boulanger.com/ref/1147569
...
 
